[package]
name = "embedded-rust-on-stm32"
version = "0.1.0"
edition = "2024"

[features]
default = []

[[bin]]
name = "embedded-rust-on-stm32"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.10.0", features = ["executor-thread", "platform-cortex-m", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime-us"] }
embassy-nrf = { version = "0.10.0", default-features = false, features = ["rt", "nrf52840", "gpiote", "time-driver-rtc1", "defmt"] }
defmt = "1.1.0"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
